server:
  port: 8200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    hikari:
      maximum-pool-size: 10

mybatis:
  mapper-locations: classpath*:/mybatis/*.xml
  type-aliases-package: com.theopendle.spring.demo.model

